site_name: antv199

nav:
  - Home: "index.md"
  - Portofolio: "portofolio.md"
  - My Knowledge Base:
      - Overview: "knowledge-base/index.md"
      - Self-hosting:
          - Jellyfin:
              - NVIDIA Hardware Acceleration for Jellyfin: "knowledge-base/selfhosting/jellyfin/nvidia-hard-accel.md"
      - Games:
          - Helldivers 2: "knowledge-base/games/helldivers2.md"
          - Borderlands GOTY: "knowledge-base/games/borderlandsgoty.md"
      - Windows Fixes:
          - Game Bar: "knowledge-base/windows-fixes/game-bar.md"
          - New Context Menu: "knowledge-base/windows-fixes/new-context-menu.md"
          - Microsoft Store: "knowledge-base/windows-fixes/microsoft-store.md"
      - Meta Quest 3/3S:
          - Performance Tips: "knowledge-base/quest3-3s/performance-tips.md"
  - Projects:
      - Websites:
          - Movie Tracking: "projects/websites/movie-tracking.md"
      - Apps:
          - Cooking App: "projects/apps/cooking-app.md"
      - IoT & Embedded:
          - Environment Monitor: "projects/embedded/enviroment-monitor.md"

theme:
  features:
    - navigation.top
    - content.tabs.link
  name: material
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#  palette: gruvbox_dark
#  features:
#   - navigation.side.indexes
#   - revision.date
#   - revision.history
markdown_extensions:
  - toc:
      # baselevel: "3"
      toc_depth: "3"
      permalink: "#"

  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite

  - pymdownx.blocks.details:
      types:
        - name: info
          class: terminal-alert
          title: Info
        - name: warning
          class: "terminal-alert terminal-alert-error"
          title: Warning
        - name: important
          class: "terminal-alert terminal-alert-primary"
          title: Important
